name: mipoka
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  syncfusion_flutter_signaturepad: ^21.2.3
  file_picker: ^5.2.11
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  crypto: ^3.0.3
  dartz: ^0.10.1
  http: ^0.13.5
  get_it: ^7.2.0
  path_provider: ^2.0.8
  datetime_picker_formfield: ^2.0.1
  docx_template: ^0.3.4
#  syncfusion_flutter_pdfviewer: ^21.2.3
  pdf_render: ^1.4.0
  flutter_quill: ^7.2.8
  firebase_storage: ^11.2.3
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  fluttertoast: ^8.2.2
  cached_network_image: ^3.2.0
  flutter_file_downloader: ^1.1.2
  pointycastle: ^3.7.3

  downloads_path_provider_28: ^0.1.2

  permission_handler: ^10.4.1
  dio: ^4.0.4
  #unused
  device_info: ^2.0.2

  excel: ^2.1.0
  universal_html: ^2.2.3
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: helvetica
      fonts:
        - asset: assets/font/helvetica.ttf
  assets:
    - assets/icons/excel.png
    - assets/icons/pdf.png
    - assets/icons/word.png
    - assets/icons/home.png
    - assets/icons/upload.png
    - assets/icons/attach.png
    - assets/icons/filter.png
    - assets/icons/approve.png
    - assets/icons/close.png
    - assets/icons/edit.png
    - assets/icons/delete.png
    - assets/icons/calendar.png
    - assets/icons/notification.png
    - assets/icons/exit.png
    - assets/icons/time.png
    - assets/icons/sms.png
    - assets/icons/light-mode.png
    - assets/icons/dark-mode.png

    - assets/json_file/admin.json
    - assets/json_file/admin_list.json

    - assets/json_file/berita.json
    - assets/json_file/berita_list.json

    - assets/json_file/kegiatan_per_periode_mpt.json
    - assets/json_file/kegiatan_per_periode_mpt_list.json

    - assets/json_file/laporan.json
    - assets/json_file/laporan_list.json

    - assets/json_file/mipoka_user.json
    - assets/json_file/mipoka_user_list.json

    - assets/json_file/ormawa.json
    - assets/json_file/ormawa_list.json

    - assets/json_file/periode_mpt.json
    - assets/json_file/periode_mpt_list.json

    - assets/json_file/prestasi.json
    - assets/json_file/prestasi_list.json

    - assets/json_file/revisi_laporan.json

    - assets/json_file/revisi_usulan.json

    - assets/json_file/riwayat_kegiatan_mpt.json
    - assets/json_file/riwayat_kegiatan_mpt_list.json

    - assets/json_file/session.json
    - assets/json_file/session_list.json

    - assets/json_file/usulan_kegiatan.json
    - assets/json_file/usulan_kegiatan_list.json

    - assets/json_file/jenis_kegiatan_mpt_list.json
    - assets/json_file/jenis_kegiatan_mpt.json

    - assets/json_file/nama_kegiatan_mpt.json
    - assets/json_file/nama_kegiatan_mpt_list.json

    - assets/json_file/mhs_per_periode_mpt.json
    - assets/json_file/mhs_per_periode_mpt_list.json

    - assets/docx_template/usulan_template.docx
    - assets/docx_template/template.docx
    - assets/docx_template/test.jpg
